apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: webapi-deployment
spec:
  selector:
    matchLabels:
      app: webapi
  replicas: 2 
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: 3mlocal.azurecr.io/webapi:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapi
spec:
  ports:
  - port: 6379
  selector:
    app: webapi
